apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata: 
    name:  epicview.info-tls
spec:
    secretName: epicview.info
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: epicview.info
    dnsNames:
        - epicview.info
        - www.epicview.info       
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - epicview.info
                - www.epicview.info 
            

            
    
       
       
       
    